name: CompLobbyManager
description: This plugin is to go on the lobby server
author: Schmoller
version: ${plugin.version}

main: au.com.addstar.comp.lobby.LobbyPlugin
depend: [ProtocolLib, Monolith]

permissions:
  comp.admin:
    default: OP
  comp.whitelist.admin:
    default: OP

commands:
  compadmin:
    permission: comp.admin
    usage: /<command> <subcommand> ...