name: CompLobbyManager
description: This plugin is to go on the lobby server
author: Schmoller
version: ${plugin.version}

main: au.com.addstar.comp.lobby.LobbyPlugin
depend: [ProtocolLib, Monolith]

permissions:
  comp.admin:
    default: OP
  comp.whitelist.admin:
    default: OP
  comp.admin.list:
    default: OP
  comp.admin.reload:
    default: OP
  comp.admin.sign:
    default: OP
  comp.admin.info:
    default: OP

commands:
  compadmin:
    permission: comp.admin
    usage: /<command> <subcommand> ...