name: CompManager
description: This plugin is to go on all comp servers to handle running comps
author: Schmoller
version: ${plugin.version}

main: au.com.addstar.comp.CompPlugin
depend: [ProtocolLib, Monolith]

# TODO: standardise permissions
permissions:
  comp.admin:
    default: OP
  comp.whitelist.admin:
    default: OP
  comp.enter.bypass:
    default: OP
  comp.build.bypass:
    default: OP
  comp.admin.reload:
    default: OP
  comp.join:
    default: true

commands:
  compadmin:
    permission: comp.admin
    usage: /<command> <subcommand> ...
  compjoin:
    permission: comp.join
    usage: /<command>
  compagree:
    aliases: [agree]
    usage: /<command>
  