name: CompManager
description: This plugin is to go on all comp servers to handle running comps
author: Schmoller
version: ${plugin.version}

main: au.com.addstar.comp.CompPlugin
depend: [ProtocolLib, Monolith]

permissions:
  comp.admin:
    default: OP
  comp.whitelist.admin:
    default: OP

commands:
  compadmin:
    permission: comp.admin
    usage: /<command> <subcommand> ...