name: CompManager
description: This plugin is to go on all comp servers to handle running comps
author: Schmoller
version: ${plugin.version}
api-version: ${spigot.api.version}

main: au.com.addstar.comp.CompPlugin
depend: [ProtocolLib, Monolith, PlotSquared]
softdepend: [PlaceholderAPI]

# TODO: standardise permissions
permissions:
  comp.admin:
    default: op
  comp.whitelist.admin:
    default: op
  comp.enter.bypass:
    default: op
  comp.build.bypass:
    default: op
  comp.admin.reload:
    default: op
  comp.join:
    default: true
  comp.admin.state:
    default: op
  comp.admin.tallyvotes:
    default: op

commands:
  compadmin:
    permission: comp.admin
    usage: /<command> <subcommand> ...
  compjoin:
    permission: comp.join
    usage: /<command>
  compagree:
    aliases: [agree]
    usage: /<command>
  compinfo:
    usage: /<command>
  compvote:
    usage: /<command> <args>